### ISSUE TITLE
sample pronunciation variants corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#389]
OK, I decided it would be better to just create a fake "spontaneous speech corpus" with actual pronunciation variants of words we might want to test. So I recorded a bunch of words and created a TextGrid file with them all in it. But when trying to import to PCT, I get the following:

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 165, in run
    **kwargs)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/io/spontaneous.py", line 330, in import_spontaneous_speech_corpus
    v['speaker'], delimiter)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/io/spontaneous.py", line 104, in textgrids_to_data
    tg.read(path)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 691, in read
    source.readline() # header junk
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/utf_16.py", line 67, in _buffer_decode
    raise UnicodeError("UTF-16 stream does not start with BOM")
UnicodeError: UTF-16 stream does not start with BOM

Presumably this is an error on my end in the encoding, but I didn't use any IPA, etc., just regular Buckeye-like transcriptions.

Here's a link to the TextGrid and sound file:
https://www.dropbox.com/s/r7g2w2pqy5357ok/pronunc_variants_corpus.TextGrid?dl=0
https://www.dropbox.com/s/tksby0e5qx1tvmf/pronunc_variants_corpus.wav?dl=0

(They're also in the test files Dropbox folder, under "Pronunc_Variants".)

(The Word tier is "words" and the phones are "actualPron"; the phone delimiter is ".", and there are multiple phones per interval.)

**Comment by mmcauliffe** [comment]
It should be working there now.  It was caused by a bug that came up for trying to get Phon textgrids to be importable.  They apparently export with UTF-16, rather than UTF-8, for some reason.  Sorry about that!  This was all on develop, right?

**Comment by kchall** [comment]
Yep, all on develop, and it seems to work now -- thanks! Will work on getting actual pronunciation variants calculations for you.
