### ISSUE TITLE
decoding error on loading corpus from formatted text file

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#403]
In reading in the Korean corpus, pre-formatted in our standard corpus format (on the develop branch):

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/decorators.py", line 12, in do_check
    function(*args,**kwargs)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 1604, in updateName
    atts, coldelim = inspect_csv(self.pathWidget.value())
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/io/csv.py", line 25, in inspect_csv
    head = f.readline().strip()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 33: ordinal not in range(128)

-I assume this has to do with the encoding of the Hangul, although that seems odd considering it had been working ok before. When I replace the Hangul with arbitrary English characters, everything works ok.

-The .txt file with actual Hangul characters also works fine in the executable version of PCT.

**Comment by mmcauliffe** [comment]
Whoops, should be fixed with the latest commit on develop!

**Comment by kchall** [comment]
Yup, looks good -- thanks!
