### ISSUE TITLE
show complete inventory even if not in IPA chart

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#407]
Currently, if a symbol DOES have features associated with it but (1) that set of features doesn't line up with PCT's expectations about IPA charts, and (2) the rest of the inventory DOES line up, then that symbol is not shown anywhere as part of the inventory. For instance: in the French Lexique corpus, the feature system is our standard Hayes system, and so most of the symbols show up fine. But there's no "slot" for nasal vowels in the IPA inventory, so they just don't show up at all as sounds that can be selected (they're not listed as "other" as they would be if they just didn't have features). (Obviously, they can still be selected featurally, but it would be good to have them at least show up in the inventory! especially for doing things like getting basic type / token frequency for each sound in the Summary window.)

**Comment by kchall** [comment]
Perhaps relatedly: I set up a custom feature system for Lexique that includes an archi-phonemic representation of some segments (i.e., uses "Q" as a cover for a set of disjunct segments), and now I get the following error when trying to build an environment -- the environment window won't display at all, and gives:

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1420, in envPopup
    dialog = EnvironmentDialog(self.inventory,self)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1289, in __init__
    self.lhs = InventoryBox('',self.inventory)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/widgets.py", line 842, in __init__
    col = consColMapping[cat[1]]
KeyError: None
