### ISSUE TITLE
Error in calculating ProD with new environments selection

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#427]
Buckeye corpus
Calculating ProD of t/d and th/dh 
Environments: 
-word-initial
-word-final
-between vowels (+syllabic)

Error:

"Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/pdgui.py", line 45, in run
    call_back = kwargs['call_back'])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/prod/pred_of_dist.py", line 132, in calc_prod
    raise(PCTError("Middle segments of all environments must be the same."))
NameError: name 'PCTError' is not defined"

(Note of course that the middle segments are getting defined in the pairs list and in fact can't be defined in the environments box.)

**Comment by mmcauliffe** [comment]
Should be fixed now.

**Comment by kchall** [comment]
Well, we have progress... I get a new error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/pdgui.py", line 45, in run
    call_back = kwargs['call_back'])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/prod/pred_of_dist.py", line 134, in calc_prod
    returned = check_envs(corpus_context, envs, stop_check, call_back)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/prod/pred_of_dist.py", line 21, in check_envs
    call_back(0,len(corpus))
NameError: name 'corpus' is not defined

**Comment by mmcauliffe** [comment]
Should be fixed now?

**Comment by kchall** [comment]
Yes, thanks!
