### ISSUE TITLE
Abstract CV tier error

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#438]
In trying to preview and then create a CV skeleton tier in the example corpus:

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 556, in preview
    segList = {'C' : [x.symbol for x in self.corpus.inventory
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 557, in <listcomp>
    if x.category is not None
AttributeError: 'Segment' object has no attribute 'category'

**Comment by mmcauliffe** [comment]
Should be fixed now!
