### ISSUE TITLE
error in TextGrid directory?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#442]
Trying to import a corpus from TextGrids (in this case, three Textgrids from the CSJ, in a directory):

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/decorators.py", line 12, in do_check
    function(*args,**kwargs)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/iogui.py", line 679, in inspect
    anno_types = inspect_discourse_textgrid(self.pathWidget.value())
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 35, in inspect_discourse_textgrid
    tg = load_textgrid(t)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 77, in load_textgrid
    tg.read(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/TextGrid-1.0-py3.4.egg/textgrid/textgrid.py", line 736, in read
    itie.addPoint(Point(jtim, jmrk))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/TextGrid-1.0-py3.4.egg/textgrid/textgrid.py", line 339, in addPoint
    raise ValueError(point)# we already got one right there
ValueError: Point(1063.61532, EUAP)

**Comment by mmcauliffe** [comment]
Should be fixed!

It takes a while to inspect the CSJ, since it's huge.  It might be worth it to add a progress bar or something to it at some point.
