### ISSUE TITLE
can't load inventory with no feature chart

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#452]
Opened the Lezgian corpus, with no feature system. Went to calculate functional load and tried to add segments:

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1828, in segPairPopup
    dialog = SegmentPairDialog(self.inventory)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1616, in __init__
    self.inventoryFrame = SegmentSelectionWidget(self.inventory)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1183, in __init__
    self.inventoryFrame = InventoryBox('', self.inventory)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1240, in __init__
    self.consonantColumns = inventory.places
AttributeError: 'Inventory' object has no attribute 'places'

(Segments should be addable even without a feature chart, just unorganized.)

**Comment by mmcauliffe** [comment]
This should be fixed, correct?  Let me know if it's still bugged.

**Comment by kchall** [comment]
yep, looks good, thanks
