### ISSUE TITLE
error with most frequent forms in Buckeye corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#454]
Trying to calculate functional load on f/v based on most frequent forms in the Buckeye corpus:

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/flgui.py", line 62, in run
    res = func(c, in_list, **kwargs)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/funcload/functional_load.py", line 79, in minpair_fl
    call_back(0, len(corpus_context))
  File "/Users/kchall/Desktop/CorpusTools/corpustools/contextmanagers.py", line 61, in __len__
    for w in self:
  File "/Users/kchall/Desktop/CorpusTools/corpustools/contextmanagers.py", line 250, in __iter__
    if v_longest1 == v_longest:
NameError: name 'v_longest' is not defined

**Comment by mdfry** [comment]
Should be fixed.
