### ISSUE TITLE
Phonotactic probability

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#503]
Develop branch, Example corpus -- calculate phonotactic probability on whole corpus:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/ppgui.py", line 59, in run
    call_back = kwargs['call_back'])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/phonoprob/phonotactic_probability.py", line 48, in phonotactic_probability_all_words
    setattr(w.original, corpus_context.attribute.name,res)
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by kchall** [comment]
And if you do it in the Buckeye corpus and select most frequent forms:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/ppgui.py", line 59, in run
    call_back = kwargs['call_back'])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/phonoprob/phonotactic_probability.py", line 33, in phonotactic_probability_all_words
    call_back(0,len(corpus_context))
  File "/Users/KCH/Desktop/CorpusTools/corpustools/contextmanagers.py", line 61, in __len__
    for w in self:
  File "/Users/KCH/Desktop/CorpusTools/corpustools/contextmanagers.py", line 250, in __iter__
    if v_longest1 == v_longest:
NameError: name 'v_longest' is not defined

@mdfry

**Comment by mdfry** [comment]
Fixed!
