### ISSUE TITLE
Add pair of segments based on features

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#504]
DevelopInventory Branch -- same as #469 

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1792, in updateSegments
    feature_values = self.inventory.find_min_feature_pairs(features, others)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1506, in find_min_feature_pairs
    if seg1.minimal_difference(seg2, features + redundant):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 63, in minimal_difference
    for k, v in self.features.items():
AttributeError: 'Segment' object has no attribute 'items'

**Comment by jsmackie** [comment]
This should be fixed in developInventoryView
