### ISSUE TITLE
Problems loading from running text

### ISSUE THREAD

**Issue by jsmackie** [PhonologicalCorpusTools/CorpusTools#512]
When loading the attached file as type "from running text"
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\main.py", line 199, in do_check
    function(self)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\main.py", line 287, in loadCorpus
    if self.corpus.specifier is None:
AttributeError: 'Discourse' object has no attribute 'specifier'
[test_text_spelling.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/180429/test_text_spelling.txt)

**Comment by jsmackie** [comment]
Some of this issue has been addressed, and loading from Transcription shouldn't be a problem anymore. 

Loading a running text as orthography creates blank transcriptions, which are a problem for swapping into a feature system later. It also causes errors if the user tries to use the right-click menu to edit transcriptions from the main window.
