### ISSUE TITLE
Uncategorized segments -- show features

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#514]
when double-clicking an uncategorized segment:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/views.py", line 852, in showFeatures
    features = [value+key for (key,value) in seg.features.items()]
AttributeError: 'Segment' object has no attribute 'items'

**Comment by kchall** [comment]
Also: when switching feature systems around:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 210, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 458, in showFeatureSystem
    self.corpusModel.corpus.retranscribe(dialog.segmap)#this also updates the corpus inventory
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 1844, in retranscribe
    T = Transcription([segmap[seg] for seg in self.wordlist[word].transcription])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 1844, in <listcomp>
    T = Transcription([segmap[seg] for seg in self.wordlist[word].transcription])
KeyError: 't'

**Comment by kchall** [comment]
(Also, could the uncategorized segments be organized vertically in their box instead of horizontally?)

**Comment by jsmackie** [comment]
I think that the first two bugs are fixed now. I'm going to move the third part, about the organization of the inventory charts, into its own issue
