### ISSUE TITLE
Sample textgrid not working

### ISSUE THREAD

**Issue by jsmackie** [PhonologicalCorpusTools/CorpusTools#554]
Loading from CorpusTools/tests/data/textgrids/pronunc_variants_corpus.TextGrid fails

Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\decorators.py", line 12, in do_check
    function(*args,**kwargs)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\iogui.py", line 716, in inspect
    anno_types = inspect_discourse_textgrid(self.pathWidget.value())
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\corpus\io\textgrid.py", line 93, in inspect_discourse_textgrid
    tg = load_textgrid(t)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\corpus\io\textgrid.py", line 135, in load_textgrid
    tg.read(path)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\corpus\io\textgrid.py", line 41, in read
    jmrk = _getMark(source)
NameError: name '_getMark' is not defined

**Comment by jsmackie** [comment]
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\iogui.py", line 91, in run
    corpus = load_discourse_textgrid(**self.kwargs)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\corpus\io\textgrid.py", line 277, in load_discourse_textgrid
    data = textgrid_to_data(path, annotation_types, call_back, stop_check)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\corpus\io\textgrid.py", line 175, in textgrid_to_data
    for si in spelling_tier:
TypeError: 'NoneType' object is not iterable

**Comment by jsmackie** [comment]
Strangely, the example file 2speakers.TextGrid will load IFF you change the spelling tier to a transcription tier, and choose None in the feature file drop-down menu. However, the corpus loads completely blank. If you pick a feature system, instead of using None, then there's a CorpusIntegrityError raised:

Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 1445, in generateGenericNames
    sample = random.choice([seg for seg in self.segs.values() if not seg.symbol == '#'])
  File "C:\Python34\lib\random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\main.py", line 192, in do_check
    function(self)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\main.py", line 335, in loadCorpus
    self.inventoryModel = InventoryModel(self.corpusModel.corpus.inventory, copy_mode=False)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 918, in __init__
    self.generateGenericNames()
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 1448, in generateGenericNames
    raise CorpusIntegrityError('No segments were found in the inventory')
corpustools.exceptions.CorpusIntegrityError: No segments were found in the inventory

**Comment by jsmackie** [comment]
Narrowed down the problem some more. This will work if you select one transcription as the actual Transcription, and set the other to "ignore". Setting the other to "Other (character)" raises a KeyError:

Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\iogui.py", line 90, in run
    corpus = load_discourse_textgrid(**self.kwargs)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\corpus\io\textgrid.py", line 287, in load_discourse_textgrid
    discourse = data_to_discourse(data, lexicon, call_back=call_back, stop_check=stop_check)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\corpus\io\helper.py", line 407, in data_to_discourse
    att = attribute_mapping[add_key]
KeyError: 'Other (character)'

**Comment by jsmackie** [comment]
This is just about working again. The only problem is that if you don't explicitly name something "Transcription" and "Spelling", you get two empty columns with those names anyway.
