### ISSUE TITLE
Add to results table bug

### ISSUE THREAD

**Issue by jsmackie** [PhonologicalCorpusTools/CorpusTools#556]
Using "update current results table" can sometimes result in an exception being raised. 

Trying to update the phonological results table:

Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\views.py", line 803, in redo
    self.table.model().addRows(self.dialog.results)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 577, in addRows
    self.allData.update(rows)
AttributeError: 'list' object has no attribute 'update'

Trying to update the results of a PROD analysis. This list of KeyError actually loops several times. The results window is updated with blank lines.

Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]
KeyError: 0
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]
KeyError: 1
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]
KeyError: 2
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]
KeyError: 3
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]
KeyError: 4
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]
KeyError: 5
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]
KeyError: 6
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]
KeyError: 7
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]
KeyError: 8
Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 46, in data
    data = self.rows[row][col]

**Comment by jsmackie** [comment]
Fixed phonological search
