### ISSUE TITLE
Getting features / partial matches doesn't always work

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#566]
When managing the inventory window (in the Lemurian corpus, with ipa2hayes):

-I removed all categorizations;
-The segments correctly show up in the "uncategorized" tab;
-Double-clicking the vowel "a" shows the correct information (partial matches, all feature specifications);
-Double-clicking the boundary symbol shows the correct information ("this can't be matched as it has no features);
-Double-clicking any of the other segments (consonants or vowels) gives the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/views.py", line 868, in showFeatures
    windowTitle, text = self.model().getPartialCategorization(seg)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1967, in getPartialCategorization
    features = [value + key for (key, value) in seg.features.items()]
AttributeError: 'Segment' object has no attribute 'items'

**Comment by kchall** [comment]
I reloaded ipa2hayes and this seems to work...
