### ISSUE TITLE
error loading ILG corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#574]
Trying to create an ILG corpus from this file:
[ilg_sample.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/342624/ilg_sample.txt)

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 85, in run
    corpus = load_discourse_ilg(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/text_ilg.py", line 235, in load_discourse_ilg
    discourse = data_to_discourse(data, lexicon, call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/helper.py", line 428, in data_to_discourse
    wordtoken = WordToken(**word_token_kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/spontaneous.py", line 446, in __init__
    if att.is_default:
UnboundLocalError: local variable 'att' referenced before assignment

**Comment by kchall** [comment]
The error message when I try to create this corpus has now changed:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 85, in run
    corpus = load_discourse_ilg(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/text_ilg.py", line 234, in load_discourse_ilg
    stop_check, call_back)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/text_ilg.py", line 172, in ilg_to_data
    for i, s in enumerate(cur_line[word_name]):
KeyError: 'spelling'
