### ISSUE TITLE
error loading sample Buckeye corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#575]
error in loading the sample of the Buckeye corpus available here:
https://www.dropbox.com/sh/oti1842xc21rcgj/AACFgWrnVhkLnWO0WKJvxUzSa?dl=0

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 96, in run
    corpus = load_directory_multiple_files(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/multiple_files.py", line 207, in load_directory_multiple_files
    stop_check, None)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/multiple_files.py", line 254, in load_discourse_multiple_files
    call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/multiple_files.py", line 107, in multiple_files_to_data
    expected = w[n]
KeyError: 'Transcription (alternative)'

**Comment by kchall** [comment]
The error message has now changed to:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 96, in run
    corpus = load_directory_multiple_files(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/multiple_files.py", line 207, in load_directory_multiple_files
    stop_check, None)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/multiple_files.py", line 254, in load_discourse_multiple_files
    call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/multiple_files.py", line 132, in multiple_files_to_data
    value = w[at.name]
KeyError: 'Other (character)'

**Comment by kchall** [comment]
Still getting an error with this, though it is now:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 101, in run
    corpus = load_directory_multiple_files(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/multiple_files.py", line 211, in load_directory_multiple_files
    stop_check, None)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/multiple_files.py", line 264, in load_discourse_multiple_files
    discourse = data_to_discourse(data, lexicon, call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/helper.py", line 511, in data_to_discourse
    name = data.name, wav_path = data.wav_path)
TypeError: __init__() got an unexpected keyword argument 'spelling_name'

**Comment by kchall** [comment]
I can now load the corpus, but this error pops up in the background:
Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 201, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 369, in loadCorpus
    self.inventoryModel = None if self.corpusModel.corpus.specifier is None else self.generateInventoryModel()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 385, in generateInventoryModel
    inventoryModel = InventoryModel(self.corpusModel.corpus.inventory, copy_mode=False)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 938, in __init__
    self.sortData()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1403, in sortData
    sorted_cons_col_headers = sorted(list(self.consColumns), key=lambda x: self.cons_column_data[x][0])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1403, in <lambda>
    sorted_cons_col_headers = sorted(list(self.consColumns), key=lambda x: self.cons_column_data[x][0])
KeyError: 'Column 1'

And then when I ask for the manage inventory chart window, the window won't load and I get the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 227, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 253, in do_check
    func(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 456, in manageInventoryChart
    if not self.inventoryModel._data:
AttributeError: 'NoneType' object has no attribute '_data'

**Comment by kchall** [comment]
Seems to be working now?
