### ISSUE TITLE
error in creating abstract tier

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#577]
Tried to create an abstract (CV) tier in the example corpus; got the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 580, in accept
    self.segList = self.generateSegList()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 555, in generateSegList
    category = self.corpus.inventory.categorize(seg)
AttributeError: 'Inventory' object has no attribute 'categorize'

**Comment by jsmackie** [comment]
This seems to be working now, although there was one instance where it seemed to fail after I switched feature systems. I couldn't replicate this bug, however.
