### ISSUE TITLE
getting corpus summary if there's no feature system

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#585]
Tried to load the csv_sample corpus with no feature system (as a user would do initially). It does now load, but the following error occurs when a summary of the corpus is asked for (instead of just listing out the segmental inventory in alphabetical order):

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 220, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 792, in corpusSummary
    dialog = CorpusSummary(self,self.corpusModel.corpus, self.inventoryModel)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 160, in __init__
    self.inventorySummary = InventorySummary(corpus, inventory)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 23, in __init__
    self.segments = InventoryBox('Segments',inventory)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1483, in __init__
    cons = self.makeConsTable()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1517, in makeConsTable
    self.consTable.setColumnCount(len(self.inventory.consColumns))
AttributeError: 'NoneType' object has no attribute 'consColumns'

**Comment by kchall** [comment]
Currently (10 July) this doesn't load at all, and the following error occurs:

(Tried to load the csv_sample corpus with no feature system (as a user would do initially). Corpus wouldn't create at all):

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/decorators.py", line 12, in do_check
    function(*args,**kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 1003, in accept
    system_name_to_path(self.settings['storage'], c.specifier.name))
AttributeError: 'NoneType' object has no attribute 'name'
