### ISSUE TITLE
[S] still showing up in running text non-delimited digraphs

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#586]
[S] still sometimes shows up in the inventory window, and when it does, "Check inventory coverage" doesn't work, because it returns the following:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/featuregui.py", line 854, in checkCoverage
    elif all([f=='n' for f in corpus_inventory[seg.symbol].features.values()]):
AttributeError: 'Segment' object has no attribute 'values'

**Comment by jsmackie** [comment]
Does this happen even with the very first corpus that you load? Or does it only happen if you've already loaded other corpora that have [S] first? I have suspicions about where this bug might be coming from, and this might make a difference.

**Comment by kchall** [comment]
Yes, it's only if I've loaded another corpus first. And it turns out, if I do the running text one first, and then load the csv_sample corpus, there's an erroneous [sh] segment. Hope that helps!

**Comment by kchall** [comment]
Now, if I load the csv_sample corpus or the running text corpus, and ask for a summary, I get the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 223, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 845, in corpusSummary
    dialog = CorpusSummary(self,self.corpusModel.corpus, self.inventoryModel)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 160, in __init__
    self.inventorySummary = InventorySummary(corpus, inventory)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 23, in __init__
    self.segments = InventoryBox('Segments',inventory)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1470, in __init__
    cons = self.makeConsTable()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/widgets.py", line 1504, in makeConsTable
    self.consTable.setColumnCount(len(self.inventory.consColumns))
AttributeError: 'NoneType' object has no attribute 'consColumns'

...so I can't check to see if the original error is actually fixed.

(The summary seems to work for e.g. the example corpus though?)

**Comment by kchall** [comment]
As far as I can tell, this is fixed.
