### ISSUE TITLE
Error loading existing corpora

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#587]
Had a corpus open, tried to load the example corpus (it had already been downloaded) and got the following (got the same thing trying to load in pre-loaded IPHOD, Lemurian, or other corpora):

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 45, in run
    results = unpickler.load()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/binary.py", line 176, in load
    dispatch[key[0]](self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 1503, in load_build
    setstate(state)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 2275, in __setstate__
    raise(e)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 2266, in __setstate__
    setattr(w,a.name,Transcription(getattr(w,a.name)))
AttributeError: can't set attribute

**Comment by kchall** [comment]
Currently:

-Lemurian and IPHOD open, but with blank spelling and transcription columns:

![image](https://cloud.githubusercontent.com/assets/7317450/16716690/a868be2e-46c9-11e6-9d28-b129f1d8c4c4.png)

The same thing happened with the example corpus, so I tried re-downloading it, and got the following error when trying to open it: 

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 46, in run
    results = unpickler.load()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/binary.py", line 176, in load
    dispatch[key[0]](self)
KeyError: 60
