### ISSUE TITLE
Error when loading TextGrids

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#591]
Tried to create a TextGrid corpus from the WebMAUS_English_story_123 TextGrid and got the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 93, in run
    corpus = load_discourse_textgrid(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 282, in load_discourse_textgrid
    data = textgrid_to_data(path, annotation_types, call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 180, in textgrid_to_data
    for si in spelling_tier:
TypeError: 'NoneType' object is not iterable

(It is still the case that at least 95% of the time when I even click on a TextGrid file in the loading menu, PCT just quits. I tried making a new TextGrid, and get the same problem.)

**Comment by jsmackie** [comment]
@kchall can you check if this is still a problem in the most recent develop commit?

**Comment by kchall** [comment]
Unfortunately, yes, it is.

**Comment by kchall** [comment]
Still getting this error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 93, in run
    corpus = load_discourse_textgrid(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 296, in load_discourse_textgrid
    data = textgrid_to_data(corpus_name, path, annotation_types, call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 182, in textgrid_to_data
    for si in spelling_tier:
TypeError: 'NoneType' object is not iterable

**Comment by kchall** [comment]
And I get this error loading the pronunc_variants corpus from the "Tests" directory:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 93, in run
    corpus = load_discourse_textgrid(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 296, in load_discourse_textgrid
    data = textgrid_to_data(corpus_name, path, annotation_types, call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 193, in textgrid_to_data
    for ti in t:
TypeError: 'NoneType' object is not iterable

**Comment by jsmackie** [comment]
The webmaus corpus loads now, and the spelling column is correct, but the transcription columns only show one symbol instead of the entire transcription

**Comment by jsmackie** [comment]
This should fix things. In order to make the "mau" transcription appear properly, you need to make the sequence <p:> the transcription delimiter (you don't also have to add it to the digraph list - the parser will figure that out).

**Comment by kchall** [comment]
Hmm, I still get the same old error with WebMAUS_123:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 94, in run
    corpus = load_discourse_textgrid(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 305, in load_discourse_textgrid
    data = textgrid_to_data(corpus_name, path, annotation_types, call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 182, in textgrid_to_data
    for si in spelling_tier:
TypeError: 'NoneType' object is not iterable

**Comment by jsmackie** [comment]
Here's a screenshot of what things look like for me right now, using the English_story_123 file. Everything seems to be working on my side. The words in the text are ordered correctly, the correct number of variants is displayed, and the "find tokens" function works. Of course, that's no guarantee of anything on anyone else's computer, apparently, so I'll just cross my fingers.

![image](https://cloud.githubusercontent.com/assets/7388097/18601738/ad181d2c-7c19-11e6-81de-3282fc002685.png)

**Comment by kchall** [comment]
I am going to declare this closed, because I was able to successfully load the WebMAUS 114 TextGrid, though at the moment I'm still having the problem of PCT crashing when I click on any .TextGrid file...

**Comment by kchall** [comment]
Argh, I'm getting the original error again:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 95, in run
    corpus = load_discourse_textgrid(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 308, in load_discourse_textgrid
    data = textgrid_to_data(corpus_name, path, annotation_types, call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 187, in textgrid_to_data
    for si in spelling_tier:
TypeError: 'NoneType' object is not iterable

Is it possible that in addressing #614, something got re-broken?

**Comment by kchall** [comment]
seems to be fixed!
