### ISSUE TITLE
backwards compatibility?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#593]
In trying to load pre-existing corpora, I'm getting lots of errors of the following type, which looks like PCT isn't checking for backwards compatibility. These are just errors that pop up in IDLE, not ones reported to the user, which means that users may not realize what needs to happen.

1. Loading Lezgian / KNC:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/random.py", line 253, in choice
    i = self._randbelow(len(seq))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/random.py", line 230, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1478, in generateGenericNames
    sample = random.choice([seg for seg in self.segs.values() if not seg.symbol == '#'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 197, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 347, in loadCorpus
    self.inventoryModel = self.generateInventoryModel()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 365, in generateInventoryModel
    inventoryModel = InventoryModel(self.corpusModel.corpus.inventory, copy_mode=False)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 943, in __init__
    self.generateGenericNames()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1481, in generateGenericNames
    raise CorpusIntegrityError('No segments were found in the inventory')
corpustools.exceptions.CorpusIntegrityError: No segments were found in the inventory

2. Loading Lezgian with forced update:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 230, in forceUpdate
    self.corpus = modernize.force_update(self.corpus)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/modernize.py", line 39, in force_update
    corpus.remove_word()
TypeError: remove_word() missing 1 required positional argument: 'word_key'

**Comment by kchall** [comment]
Just tried this again with the KNC and got the following (different) error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 201, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 335, in loadCorpus
    self.corpus = self.forceUpdate(self.corpus)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 406, in forceUpdate
    corpus.update_wordlist(word_list)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 1995, in update_wordlist
    self.add_word(word)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 2538, in add_word
    word.frequency += 1
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 385, in __add__
    raise(TypeError)
TypeError

The Lezgian corpus correctly loaded and seems to have been automatically updated.

**Comment by kchall** [comment]
now working?
