### ISSUE TITLE
IPHOD corpus not loading

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#599]
I tried to download and load the IPHOD corpus. It downloaded ok, but I got the following error when trying to open:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 46, in run
    results = unpickler.load()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/binary.py", line 176, in load
    dispatch[key[0]](self)
KeyError: 60

**Comment by kchall** [comment]
Sorry, realized I hadn't synced to last night's version. All ok.
