### ISSUE TITLE
Problem with inventory window / feature system with KNC

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#609]
Opened the attached KNC corpus with the worldbet2shin feature file. Originally, the "corpus summary" window was all blank (not even any uncategorized segments) and I couldn't open the "manage inventory chart" window (I got the "you can normally fix this..." message). I opened the feature system and saved it. This made the uncategorized segments show up in the corpus summary window, but I continue to be unable to open the "manage inventory chart" window.

In the feature system window, if I choose "Check corpus inventory coverage," I get the following errors:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 227, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 551, in showFeatureSystem
    self.inventoryModel.updateFeatures(dialog.specifier)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1014, in updateFeatures
    self.modelReset()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1317, in modelReset
    self.sortData()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1403, in sortData
    sorted_cons_col_headers = sorted(list(self.consColumns), key=lambda x: self.cons_column_data[x][0])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1403, in <lambda>
    sorted_cons_col_headers = sorted(list(self.consColumns), key=lambda x: self.cons_column_data[x][0])
KeyError: 'Labial'
Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 227, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 551, in showFeatureSystem
    self.inventoryModel.updateFeatures(dialog.specifier)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1014, in updateFeatures
    self.modelReset()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1317, in modelReset
    self.sortData()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1403, in sortData
    sorted_cons_col_headers = sorted(list(self.consColumns), key=lambda x: self.cons_column_data[x][0])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1403, in <lambda>
    sorted_cons_col_headers = sorted(list(self.consColumns), key=lambda x: self.cons_column_data[x][0])
KeyError: 'Labial'
Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/featuregui.py", line 856, in checkCoverage
    elif all([f=='n' for f in corpus_inventory[seg.symbol].features.values()]):
AttributeError: 'Segment' object has no attribute 'values'

[KNC_corpus_for_PCT.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/549216/KNC_corpus_for_PCT.txt)

[worldbet2shin.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/549217/worldbet2shin.txt)

**Comment by kchall** [comment]
using Scott's WorldBet2Shin.feature file, I no longer get an error when asking to check corpus inventory coverage, but it thinks there is a segment missing from the inventory window. Not being able to save the inventory may be what's causing the manage inventory window not to work?

![image](https://cloud.githubusercontent.com/assets/7317450/20287861/15efe526-aa84-11e6-9024-d87e53186733.png)
