### ISSUE TITLE
Manage feature systems?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#625]
Loaded the csv_sample.txt corpus from scratch, with NO associated feature file. Once it had been loaded, I went to "View / change feature system" to associate a feature file, but the window won't open; instead, I get the following error message:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 231, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 523, in showFeatureSystem
    oldSystem = self.corpusModel.corpus.specifier.name
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by kchall** [comment]
This seems to be a general problem with any corpus loaded without a feature system.
