### ISSUE TITLE
loading feature systems

### ISSUE THREAD

**Issue by jsmackie** [PhonologicalCorpusTools/CorpusTools#626]
created WebMaus TextGrid directory corpus; no feature system associated (should be sampa2hayes, and that was selected on import):

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/featuregui.py", line 635, in changeRestrictedFeatureSystem
    self.specifier = load_binary(path)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/binary.py", line 104, in load_binary
    with open(path,'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/KCH/Documents/PCT/CorpusTools/FEATURE/.feature'

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/featuregui.py", line 548, in acceptRestricted
    fileNameDialog = FileNameDialog(self.specifier.name, 'features', self.settings, hint=name_hint)
UnboundLocalError: local variable 'name_hint' referenced before assignment

**Comment by jsmackie** [comment]
During testing this morning, we had forgotten to select the option "Allow pronunciation to vary between lexical items". When that option is not selected, you get an empty pronunciation variants box.  Turning that on makes everything work properly in both the debug version and the Windows and Mac executable versions.
