### ISSUE TITLE
Environments

### ISSUE THREAD

**Issue by invcr** [PhonologicalCorpusTools/CorpusTools#659]
Hi,

I'm working with a corpus of Icelandic, and until now everything was going swimmingly. Now, however, when I decided to calculate FL for vowel contrasts in certain environments (word-initial), I got an error. No matter what algorithm I use, if environments are involved, I get the error. Below is the error log, which I emailed to pctbugs, but since I'm in a time crunch, I need it to get to the developers ASAP. 

**Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/flgui.py", line 57, in run
  File "/Users/KCH/Desktop/CorpusTools/corpustools/funcload/functional_load.py", line 210, in minpair_fl
  File "/Users/KCH/Desktop/CorpusTools/corpustools/funcload/functional_load.py", line 41, in is_minpair
  File "/Users/KCH/Desktop/CorpusTools/corpustools/funcload/functional_load.py", line 87, in fits_environment
  File "/Users/KCH/Desktop/CorpusTools/corpustools/funcload/functional_load.py", line 98, in make_environment_re
AttributeError: 'list' object has no attribute 'lhs'**

Any help will be greatly appreciated.

**Comment by kchall** [comment]
Thanks for reporting this! We noticed this issue ourselves (see #651), and it should currently be fixed in the Develop branch code. There were a couple of other things we were hoping to fix before re-releasing, so if you are in a hurry, using the source code would be the best way to go (and we can help with that if needed). Alternatively, we will probably be able to release the newest version in about month, I'd guess.
