### ISSUE TITLE
Error in reading directory of .txt files

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#665]
When the file path to Dropbox/Phonological_CorpusTools_Public/example_files/CSJ_sample/CSJ_text_sample is selected in the "Import corpus" dialogue box, and then one tries to actually load the corpus, the following error occurs:

Traceback (most recent call last):
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/gui/iogui.py", line 80, in run
    corpus = load_directory_transcription(**self.kwargs)
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/corpus/io/text_transcription.py", line 180, in load_directory_transcription
    stop_check, call_back)
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/corpus/io/text_transcription.py", line 220, in load_discourse_transcription
    stop_check=stop_check, call_back=call_back)
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/corpus/io/helper.py", line 498, in data_to_discourse2
    word_token_kwargs[at.attribute.name] = (at.attribute, annotations[at][n][0])
IndexError: list index out of range

**Comment by kchall** [comment]
Note: the csj2hayes.txt feature file and the list of CSJ digraphs are in the /Users/kathleenhall/Dropbox/Phonological_CorpusTools_Public/TRANS folder.

**Comment by kchall** [comment]
Just confirming that this looks to be fixed to me, too, thanks.
