### ISSUE TITLE
getting importError when installing latest 1.3.0 version

### ISSUE THREAD

**Issue by zivziv77** [PhonologicalCorpusTools/CorpusTools#666]
Hi

I am getting the following when running pct:
Traceback (most recent call last):
  File "/usr/local/bin/pct", line 9, in <module>
    load_entry_point('corpustools==1.3.0', 'console_scripts', 'pct')()
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 2355, in load
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/usr/local/lib/python3.5/dist-packages/corpustools-1.3.0-py3.5.egg/corpustools/command_line/pct.py", line 5, in <module>
    from corpustools.gui.main import MainWindow,QApplicationMessaging
  File "/usr/local/lib/python3.5/dist-packages/corpustools-1.3.0-py3.5.egg/corpustools/gui/main.py", line 21, in <module>
    from .iogui import (CorpusLoadDialog, SubsetCorpusDialog, ExportCorpusDialog, save_binary)
  File "/usr/local/lib/python3.5/dist-packages/corpustools-1.3.0-py3.5.egg/corpustools/gui/iogui.py", line 12, in <module>
    from corpustools.corpus.io.textgrid import (inspect_discourse_textgrid,
  File "/usr/local/lib/python3.5/dist-packages/corpustools-1.3.0-py3.5.egg/corpustools/corpus/io/textgrid.py", line 5, in <module>
    from textgrid.textgrid import readFile, Interval, Point, PointTier , _getMark
ImportError: cannot import name 'readFile'

**Comment by zivziv77** [comment]
Sorry, just saw someone got this problem.
I installed textgrid 1.1 and now get:
ziv@Ziv:~/CorpusTools-1.3.0$ pct
Traceback (most recent call last):
  File "/usr/local/bin/pct", line 9, in <module>
    load_entry_point('corpustools==1.3.0', 'console_scripts', 'pct')()
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 2355, in load
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/usr/local/lib/python3.5/dist-packages/corpustools-1.3.0-py3.5.egg/corpustools/command_line/pct.py", line 5, in <module>
    from corpustools.gui.main import MainWindow,QApplicationMessaging
  File "/usr/local/lib/python3.5/dist-packages/corpustools-1.3.0-py3.5.egg/corpustools/gui/main.py", line 52, in <module>
    from .infogui import InformativityDialog
  File "/usr/local/lib/python3.5/dist-packages/corpustools-1.3.0-py3.5.egg/corpustools/gui/infogui.py", line 2, in <module>
    import corpustools.informativity.informativity as informativity
ImportError: No module named 'corpustools.informativity'

**Comment by mdfry** [comment]
Thanks for the error checking. Like I mentioned in the previous error you've posted, it seems there have been some compatibility issues with packages that have been updated since we made the v1.3 executable.

For now, what *should* work is to sync to the master branch and run the pct_qt_debug.py script. You can find it in Corpustools/bin/pct_qt_debug.py

Let me know if you run into other issues.

**Comment by zivziv77** [comment]
Thank you! with the debug it works!
