### ISSUE TITLE
Look-up transcriptions doesn't work

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#668]
I received the following error message trying to look up transcriptions for words in a running text in the iphod corpus:
 
Traceback (most recent call last):
File "corpustools\gui\iogui.py", line 76, in run
File "corpustools\corpus\io\text_spelling.py", line 206, in load_discourse_spelling
File "corpustools\corpus\io\text_spelling.py", line 95, in spelling_text_to_data
IndexError: list index out of range

This has been partially fixed, but we have to get the transcriptions to be visible. Also, in trying to calculate the functional load in a resulting corpus, the following error occurs:

Traceback (most recent call last):
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/gui/flgui.py", line 57, in run
    res = func(c, in_list, **kwargs)
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/funcload/functional_load.py", line 191, in minpair_fl
    tier = getattr(w, corpus_context.sequence_type)
TypeError: getattr(): attribute name must be string

**Comment by jsmackie** [comment]
Transcriptions are showing correctly, but some analysis functions are still buggy

**Comment by kchall** [comment]
This basically looks great! One modification, though, would be to ask users what they want to have happen if there is a word 'missing' from the corpus in which words are being looked up. Currently, PCT apparently tries to 'figure out' the transcription from the orthography -- e.g., the word "This" isn't in IPHOD (because it's "this"), and the 'transcription' in the new corpus is [T.h.i.s], which obviously isn't accurate. It would probably be more useful if the transcriptions were just left blank in these cases, and then users could add them later. But, at least they should have the option.
