### ISSUE TITLE
Fallback installation

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#673]
I tried to follow the instruction on README.md (located in root folder), using Anaconda Prompt (terminal).

On the terminal I commanded python setup.py install to do the fallback installation. 

> Installed c:\programdata\anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg
> Processing dependencies for corpustools==1.3.0
> Searching for textgrid==1.4
> Best match: textgrid 1.4
> Processing textgrid-1.4-py3.6.egg
> textgrid 1.4 is already the active version in easy-install.pth
> 
> Using c:\programdata\anaconda3\lib\site-packages\textgrid-1.4-py3.6.egg
> Searching for scipy==1.1.0
> Best match: scipy 1.1.0
> Adding scipy 1.1.0 to easy-install.pth file
> 
> Using c:\programdata\anaconda3\lib\site-packages
> Searching for numpy==1.14.6+mkl
> Best match: numpy 1.14.6+mkl
> Adding numpy 1.14.6+mkl to easy-install.pth file
> 
> Using c:\programdata\anaconda3\lib\site-packages
> Finished processing dependencies for corpustools==1.3.0

Obviously PCT was properly installed.

However, when I command pct on the terminal, it crashes.

Following is the error message:

> C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\gui\asgui.py", line 9, in <module>
>     from acousticsim.main import(acoustic_similarity_mapping,
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\acousticsim\main.py", line 5, in <module>
>     from corpustools.acousticsim.representations import to_envelopes, to_mfcc
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\acousticsim\representations.py", line 7, in <module>
>     from scipy.signal import filtfilt, butter, hilbert, resample, lfilter
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\signal\__init__.py", line 323, in <module>
>     from .ltisys import *
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\signal\ltisys.py", line 31, in <module>
>     from scipy import integrate, interpolate, linalg
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\__init__.py", line 175, in <module>
>     from .interpolate import *
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 32, in <module>
>     from .interpnd import _ndim_coords_from_arrays
>   File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\spatial\__init__.py", line 95, in <module>
>     from .ckdtree import *
>   File "ckdtree.pyx", line 22, in init scipy.spatial.ckdtree
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\multiprocessing.py", line 2, in <module>
>     from multiprocessing import Process, process, Manager, Queue, cpu_count, Value, Lock, Pool, JoinableQueue
> ImportError: cannot import name 'Process'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\Scripts\pct-script.py", line 11, in <module>
>     load_entry_point('corpustools==1.3.0', 'console_scripts', 'pct')()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2691, in load_entry_point
>     return ep.load()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2322, in load
>     return self.resolve()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2328, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\command_line\pct.py", line 7, in <module>
>     from corpustools.gui.main import MainWindow,QApplicationMessaging
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\gui\main.py", line 45, in <module>
>     from .asgui import ASDialog
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\gui\asgui.py", line 14, in <module>
>     from corpustools.acousticsim.main import(acoustic_similarity_mapping,
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\acousticsim\main.py", line 5, in <module>
>     from corpustools.acousticsim.representations import to_envelopes, to_mfcc
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\acousticsim\representations.py", line 7, in <module>
>     from scipy.signal import filtfilt, butter, hilbert, resample, lfilter
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\signal\__init__.py", line 323, in <module>
>     from .ltisys import *
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\signal\ltisys.py", line 31, in <module>
>     from scipy import integrate, interpolate, linalg
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\__init__.py", line 187, in <module>
>     from .ndgriddata import *
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\ndgriddata.py", line 10, in <module>
>     from .interpnd import LinearNDInterpolator, NDInterpolatorBase, \
> ImportError: cannot import name 'LinearNDInterpolator'

**Comment by yellappadamam** [comment]
Facing same issue.. any updates.. ?
