### ISSUE TITLE
Buckeye Corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#677]
1. Speakers.corpus file can't be loaded
2. If it is loaded, the pronunciation variants aren't visible
3. The full Buckeye corpus can't be re-created: 

I get to file 202 of 244 and the following happens:

Traceback (most recent call last):
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/gui/iogui.py", line 102, in run
    corpus = load_directory_multiple_files(**self.kwargs)
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/corpus/io/multiple_files.py", line 218, in load_directory_multiple_files
    stop_check, None)
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/corpus/io/multiple_files.py", line 277, in load_discourse_multiple_files
    words = read_words(word_path, dialect)
  File "/Users/kathleenhall/Desktop/GitHub/CorpusTools/corpustools/corpus/io/multiple_files.py", line 387, in read_words
    phonetic = line[3].split(' ')
IndexError: list index out of range

4. A subset of S01 and S02 can be created, but the pronunciation variants aren't being found.

**Comment by YuHsiangLo** [comment]
Not a Python version problem --- tried with 3.5 and still didn't work.

**Comment by kchall** [comment]
Update: I can now re-create the whole corpus without the "list index" error, but pronunciation variants still don't show up on the Mac. (I can load Michael's version of the .corpus file, and that one contains the pronunciation variants.)

**Comment by mdfry** [comment]
Figure out why s1304a, s1804a, s3504a are failing to be read.
