### ISSUE TITLE
bug in functional load

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#697]
When trying to run FL using change-in-entropy, e.g. in the example corpus on [m] / [n], the following error occurs:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/flgui.py", line 57, in run
    res = func(c, in_list, **kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/funcload/functional_load.py", line 329, in deltah_fl
    call_back(0, len(list(original_probs.keys())))
UnboundLocalError: local variable 'original_probs' referenced before assignment

**Comment by stannam** [comment]
It seems to me that calculating FL with the change-in-entropy algorithm **using 'Token frequency'** does not raise this error...
