### ISSUE TITLE
Loading feature file causes error

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#708]
Trying to load the gitksan2hayes feature file from .txt causes error:

Traceback (most recent call last):
  File "/Users/YuHsiangLo/Documents/CorpusTools/corpustools/gui/featuregui.py", line 29, in run
  File "/Users/YuHsiangLo/Documents/CorpusTools/corpustools/corpus/io/csv.py", line 237, in load_feature_matrix_csv
KeyError

This one might be specific to this feature system? The ipa2hayes.txt one worked....

**Comment by stannam** [comment]
I couldn't replicate this problem. In both the latest version and ver. 1.4.0, I can load without error _gitksan2hayes.txt_ (under _TRANS_ folder).

By the way, there was the row for a symbol named 'empty.' Is it supposed to be in the file? Or might this be a cause?
![image](https://user-images.githubusercontent.com/43150234/65217196-301a6180-da68-11e9-8827-b672b901bcff.png)

**Comment by kchall** [comment]
not replicable?
