### ISSUE TITLE
FL error from user

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#721]
"When I tried to calculate FL based on "change in entropy, output normalised to corpus size, type frequency using canonical form only at initial position for /m/, this is the error:" 

Traceback (most recent call last):
  File "/Users/YuHsiangLo/Documents/CorpusTools/corpustools/gui/flgui.py", line 51, in run
  File "/Users/YuHsiangLo/Documents/CorpusTools/corpustools/funcload/functional_load.py", line 486, in relative_deltah_fl
  File "/Users/YuHsiangLo/Documents/CorpusTools/corpustools/funcload/functional_load.py", line 342, in deltah_fl
  File "/Users/YuHsiangLo/Documents/CorpusTools/corpustools/funcload/functional_load.py", line 368, in neutralize_with_all_envs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/regex.py", line 340, in finditer
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/regex.py", line 507, in _compile
_regex_core.error: nothing to repeat at position 11

**Comment by stannam** [comment]
I can't replicate this issue. :( 
![image](https://user-images.githubusercontent.com/43150234/73881223-cd5a1480-4814-11ea-8b53-1368cdfc39e2.png)

**Comment by kchall** [comment]
Me neither...I'm closing.
