### ISSUE TITLE
Buckeye Corpus Issues

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#744]
Failed to import Buckeye Corpus with the following error message

Traceback (most recent call last):
  File "D:\PycharmProjects\CorpusTools\corpustools\gui\iogui.py", line 106, in run
    corpus = load_directory_multiple_files(**self.kwargs)
  File "D:\PycharmProjects\CorpusTools\corpustools\corpus\io\multiple_files.py", line 196, in load_directory_multiple_files
    stop_check, None)
  File "D:\PycharmProjects\CorpusTools\corpustools\corpus\io\multiple_files.py", line 259, in load_discourse_multiple_files
    word = Word(**word_kwargs)
  File "D:\PycharmProjects\CorpusTools\corpustools\corpus\classes\lexicon.py", line 1129, in __init__
    if self.spelling is None and self.transcription is None:
  File "D:\PycharmProjects\CorpusTools\corpustools\corpus\classes\lexicon.py", line 1195, in spelling
    value = getattr(self, self._spelling_name, self._spelling)
  File "D:\PycharmProjects\CorpusTools\corpustools\corpus\classes\lexicon.py", line 1195, in spelling
    value = getattr(self, self._spelling_name, self._spelling)
  File "D:\PycharmProjects\CorpusTools\corpustools\corpus\classes\lexicon.py", line 1195, in spelling
    value = getattr(self, self._spelling_name, self._spelling)
  [Previous line repeated 494 more times]
RecursionError: maximum recursion depth exceeded

**Comment by stannam** [comment]
* ~~The frequency column does not reflect the word count of the dialogue~~.
* Inventory chart.
* What should it mean to "Edit word details" in Buckeye? For example, it doesn't make sense to modify frequency.
