### ISSUE TITLE
Mutual Information on Buckeye Corpus

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#751]
* Error when calculating mutual information by pronunciation variants.

> Traceback (most recent call last):
>   File "D:\PycharmProjects\CorpusTools\corpustools\gui\migui.py", line 44, in run
>     call_back = kwargs['call_back'])
>   File "D:\PycharmProjects\CorpusTools\corpustools\mutualinfo\mutual_information.py", line 197, in pointwise_mi
>     probability=True, need_wb=need_wd)
>   File "D:\PycharmProjects\CorpusTools\corpustools\contextmanagers.py", line 98, in get_frequency_base
>     tier = getattr(word, self.sequence_type)
> AttributeError: 'Word' object has no attribute 'Transcription'
>

**Comment by YuHsiangLo** [comment]
Hmmm I think this is caused by the mixing of attribute _transcription, Transcription, _transcription_name, and the transcription getter and setter... This issue is related to #756, and we'll need to do some fundamental refactoring of the Word class to solve this type of problems once and for all.

**Comment by stannam** [comment]
cf. we have a separate branch for this: 'pronunciation_variants'

**Comment by stannam** [comment]
The recent commit, the one that forces the column name (92113c5b02b884e74b6f78a131bcd50cf35553b2) gets ride of the 'Unwanted transcription column' issue (i.e., no 'canonical' column to start with). However, for an independent reason, "List pronunciation variants" is acting out again 😳. 
I have added an example file csv_pron_var.txt to the 'csv_sample' folder.
