### ISSUE TITLE
[BUG] Installation issue on Win10

### ISSUE THREAD

**Issue by Kedersha** [PhonologicalCorpusTools/CorpusTools#760]
Hi! I'm helping a user get set up with the command-line version of PCT, and we're having some trouble with the installation. We've updated Python to 3.9 and installed the required packages as far as I could tell (setuptools, PyQt5, textgrid, NumPy, SciPy), and downloaded/set up Cygwin as best we could, not having used it before.

The installation of PCT seems to go fine (it runs without errors) but then if we run `pct help` immediately after, we get the following:

```
C:\Python\Python39\Lib\site-packages\corpustools-1.4.1-py3.9.egg\corpustools
Traceback (most recent call last):
  File "C:\Python\Python39\Scripts\pct-script.py", line 33, in <module>
    sys.exit(load_entry_point('corpustools==1.4.1', 'console_scripts', 'pct')())
  File "C:\Python\Python39\Scripts\pct-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Python\Python39\lib\site-packages\corpustools-1.4.1-py3.9.egg\corpustools\command_line\pct.py", line 7, in <module>
    from corpustools.gui.main import MainWindow,QApplicationMessaging
  File "C:\Python\Python39\lib\site-packages\corpustools-1.4.1-py3.9.egg\corpustools\gui\main.py", line 9, in <module>
    import corpustools.gui.modernize as modernize
  File "C:\Python\Python39\lib\site-packages\corpustools-1.4.1-py3.9.egg\corpustools\gui\modernize.py", line 2, in <module>
    from corpustools.corpus.classes.lexicon import Corpus, Inventory, Segment, FeatureMatrix, Word
  File "C:\Python\Python39\lib\site-packages\corpustools-1.4.1-py3.9.egg\corpustools\corpus\classes\__init__.py", line 2, in <module>
    from .lexicon import (Corpus, Word, Environment, EnvironmentFilter, FeatureMatrix,
  File "C:\Python\Python39\lib\site-packages\corpustools-1.4.1-py3.9.egg\corpustools\corpus\classes\lexicon.py", line 3, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'
```

Operating system and PCT version
 - OS: Windows 10 (I can get more specifics if needed)
 - PCT version: 1.5.0b (on advice from [this thread](https://github.com/PhonologicalCorpusTools/CorpusTools/issues/699))

Is this something just wrong with our Python configuration, or are there PCT dependencies we might be missing? Related, are there specific Cygwin packages recommended for installation on a Windows machine? Thanks!

**Comment by stannam** [comment]
Hi, thanks for letting us know about this. It seems to me that the issue is from a missing package. 
Can you try installing the 'regex' package? To do this, you can type this into the command line.

`pip install regex
`

You may need admin rights to do this. I haven't tested PCT on Python 3.9 (I personally worked on 3.7), and I don't think a higher version of Python is the problem, but I will also test running PCT on the latest Python version.

**Comment by Kedersha** [comment]
Oops! I absolutely should have thought of this, thanks. I've asked the user to give it a shot, and will let you know if it worked asap. 👍

**Comment by Kedersha** [comment]
Hi again! The user installed regex then re-installed PCT, but is now getting the following traceback; I won't have a chance to do a screenshare/troubleshooting session with her this week, but if you have any suggestions off the top of your head they'd be much appreciated. Thanks!

```
Traceback (most recent call last):
  File "C:\Python\Python39\Scripts\pct-script.py", line 33, in <module>
    sys.exit(load_entry_point('corpustools==1.4.1', 'console_scripts', 'pct')())
  File "C:\Python\Python39\Scripts\pct-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Python\Python39\lib\site-packages\corpustools-1.4.1-py3.9.egg\corpustools\command_line\pct.py", line 7, in <module>
    from corpustools.gui.main import MainWindow,QApplicationMessaging
  File "C:\Python\Python39\lib\site-packages\corpustools-1.4.1-py3.9.egg\corpustools\gui\main.py", line 54, in <module>
    from .trpgui import TPDialog
  File "C:\Python\Python39\lib\site-packages\corpustools-1.4.1-py3.9.egg\corpustools\gui\trpgui.py", line 15, in <module>
    from ..transprob.transitional_probability import calc_trans_prob
ModuleNotFoundError: No module named 'corpustools.transprob'

```

**Comment by kchall** [comment]
Command line is no longer supported actively.
