### ISSUE TITLE
[ENC] Bundle feature and corpus files with the executable

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#764]
**Is your feature request related to a problem? Please describe.**
Downloading corpus and feature files can be tricky due to certificate issues. Basics files can be included in the distribution of the program itself.

**Describe the solution you'd like**
Bundle them up together!

**Describe alternatives you've considered**
Fixing the certificate issues (or let the users know how to fix them) can be an alternative solution.

**Additional context**

**Comment by stannam** [comment]
What I know so far:
 * copying corpus + feature files *fails* but PCT creates (empty) folders CORPUS and FEATURE.
   * that means **os.mkdir()** (creating folder) works, but **shutil.copy()** (copying files) doesn't.
   * currently shutil.copy uses relative path. 
   * using abs path can solve the problem.
 * creating executable has error of its own. (independent reasons)
   * my hunch is that sklearn is the culpit. (i.e., our new vectorized FL)
   * because, in the verbose mode, executable throws the following error message.
```
Traceback (most recent call last):
(...)
  File "site-packages\scipy\spatial\__init__.py", line 107, in <module>
  File "C:\Users\Stanley\anaconda3\envs\PCT\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\spatial\transform\__init__.py", line 19, in <module>
  File "rotation.pyx", line 5, in init scipy.spatial.transform.rotation
ModuleNotFoundError: No module named 'scipy.spatial.transform._rotation_groups'
```
