### ISSUE TITLE
[BUG] Negative phonological search crashes

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#797]
**Describe the bug**
Phonological search crashes when the user selects all segments and runs negative search.

**Sample corpus file**
'example' corpus

**To Reproduce**
1. Go to 'Phonological Search'
2. Select all segments from the inventory
3. Select 'negative'
4. Run search
5. See error

**Expected behavior**
A result table with one row of N/A

**Additional context**
Traceback (most recent call last):
  File "D:\PycharmProjects\CorpusTools\corpustools\gui\main.py", line 320, in do_check
    function(self)
  File "D:\PycharmProjects\CorpusTools\corpustools\gui\main.py", line 335, in do_check
    function(self)
  File "D:\PycharmProjects\CorpusTools\corpustools\gui\main.py", line 965, in phonoSearch
    'Phonological search results', dialog, self)
  File "D:\PycharmProjects\CorpusTools\corpustools\gui\views.py", line 863, in __init__
    dataModel.setSummarized(True)
  File "D:\PycharmProjects\CorpusTools\corpustools\gui\models.py", line 633, in setSummarized
    self._summarize()
  File "D:\PycharmProjects\CorpusTools\corpustools\gui\models.py", line 589, in _summarize
    tokenfreq[segenvfilters] += line['Word'].frequency  # and add token freq accordingly
TypeError: unsupported operand type(s) for +=: 'float' and 'str'

Process finished with exit code 1

**Comment by stannam** [comment]
Tested on a very simple corpus with only two words. 'A' is a column for orthography, 'C' is for frequency.

**A** | **Transcription** | **C**
-- | -- | --
a | a.a.a.a | 1
b | b | 2


1. Negative search for {a, b} (i.e., either [a] or [b])  -- expecting no words in the individual window but should have one row on the summary results
- summary results
![image](https://user-images.githubusercontent.com/43150234/149852910-f2324b21-5183-4073-b2ad-359401c75843.png)

- individual results
![image](https://user-images.githubusercontent.com/43150234/149852944-b0ca8dcf-509e-4490-ab50-aac68a22d7c2.png)

2. Negative search for [a] **on top of Search 1** 
- summary results
![image](https://user-images.githubusercontent.com/43150234/149853049-693666bd-22a8-4e11-bd4b-fc2d644aaddf.png)

- individual results
![image](https://user-images.githubusercontent.com/43150234/149853076-9993e4b1-fb9c-4975-92b2-e814d4c55295.png)

3. Negative search for [b] out of scratch
- summary results
![image](https://user-images.githubusercontent.com/43150234/149853233-dba02d56-c59f-4405-a18b-3e92a9282ff7.png)

- individual results 
![image](https://user-images.githubusercontent.com/43150234/149853246-e43f186a-795b-46b9-8e79-155f21ccac8a.png)


4. **Positive** search for [a] **on top of Search 3** (just in case)
- summary results
![image](https://user-images.githubusercontent.com/43150234/149853437-927982d4-d2f3-4a98-89c4-6cc102469b23.png)

- individual results
![image](https://user-images.githubusercontent.com/43150234/149853454-9266fa24-5d10-4ee6-b959-a4e43f889ea0.png)
